// Editorially reviewed adaptations of the supplied postgraduate article collection.
// Historical company cases are reflections, not statements of current policy or results.
const articles = [
  {
    number: 1, title: 'Why Your Stakeholder Engagement Plan Is Missing the Point',
    slug: 'stakeholder-risk-perception', category: 'Leadership & Transformation',
    seoTitle: 'Stakeholder Engagement Starts with Risk Perception | Phull Insights',
    description: 'Why stakeholder communication needs to start with perception, trust and the concerns behind resistance.',
    deck: 'The most accurate message can fail when its audience does not trust the messenger.',
    tags: ['stakeholder engagement', 'risk perception', 'change management'],
    why: 'Operational leaders often treat resistance as a communications failure: provide more data, repeat the rationale, and make the presentation clearer. But opposition to a facility, policy or technology can be rooted in trust and lived experience rather than a lack of information.',
    evidence: 'Risk perception is influenced by what people have recently seen, how a proposal is framed, and who is speaking. A communication plan that counts meetings and messages but does not listen for these drivers can look busy while leaving the central concern untouched.',
    practice: 'In the historical risk-communication exercise behind this article, the useful question was not simply what to say. It was whose concerns had been heard, which claims could be independently checked, and whether feedback would change the decision process.',
    actions: ['Interview affected groups before drafting the message, and record the concern in their own words.', 'Separate technical evidence from the question of whether the source is trusted.', 'Track how concerns change after engagement, not just how many people attended.'],
    perspective: 'Being right is not the same as being heard. The best starting point is a perception and trust diagnosis, followed by clear evidence and a visible response to what people raise.'
  },
  {
    number: 2, title: "Read the Accounts: What Jamie's Italian Taught Me About Supplier Risk",
    slug: 'read-the-accounts-supplier-risk', category: 'Supply Chain & Operations',
    seoTitle: 'Supplier Risk: What the Accounts Tell You First | Phull Insights',
    description: 'A historical restaurant-sector comparison shows why financial health belongs in strategic supplier reviews.',
    deck: 'A supplier can meet service targets while its ability to keep doing so is weakening.',
    tags: ['supplier risk', 'procurement', 'financial analysis'],
    why: 'Operations teams often know a supplier’s delivery record but not its financial resilience. That leaves a blind spot in contracts where disruption would be difficult to absorb.',
    evidence: 'The historical comparison of Jamie’s Italian and Carluccio’s showed how losses, liquidity pressure and fixed costs can make an operating model fragile. The point is not to turn every buyer into an accountant; it is to treat financial statements as one signal alongside quality, capacity and service.',
    practice: 'A useful supplier review asks whether cash generation, obligations and investment capacity support the service promise. Ratios need context, trend and professional interpretation; no single threshold reliably predicts failure.',
    actions: ['Include financial resilience in the review of suppliers that would be hard to replace.', 'Look at trends and explanations rather than treating a ratio as a pass-or-fail test.', 'Agree a contingency route while service is still stable.'],
    perspective: 'The cost of resilience is easiest to justify before a counterpart is in distress. Financial literacy is an operational capability when continuity depends on another business.'
  },
  {
    number: 3, title: 'Your Code of Conduct Does Not Cover AI: Why Boards Need a Digital Ethics Framework Now',
    slug: 'digital-ethics-framework-boards', category: 'Governance & Technology',
    seoTitle: 'Why Your Code of Conduct Needs an AI Ethics Layer | Phull Insights',
    description: 'How leaders can review the human consequences of AI, monitoring and automation alongside existing conduct rules.',
    deck: 'A rulebook written for human decisions needs a way to test digital decisions too.',
    tags: ['AI governance', 'digital ethics', 'leadership'],
    why: 'Automation can affect recruitment, performance management and customer decisions. A general commitment to fairness is useful, but it does not by itself assign responsibility for reviewing a specific use case.',
    evidence: 'The historical DHL-themed governance proposal behind this article used three lenses: duties to people, the character of the organisation, and the likely consequences of a decision. These lenses expose questions that a technical deployment checklist may miss.',
    practice: 'A cross-functional review can ask what data a tool needs, who may be disadvantaged, how a person can challenge an outcome, and which accountable leader can stop or amend the use. Legal compliance remains essential, but the ethical question may be wider.',
    actions: ['Map tools that monitor, profile or influence decisions about people.', 'Give each use case an accountable owner and a route for challenge.', 'Review the human impact before rollout and again when the use changes.'],
    perspective: 'Digital ethics works best as a decision practice, not a decorative policy. The test is whether a difficult use case can be slowed down, questioned and changed.'
  },
  {
    number: 4, title: 'When Agility Becomes Your Only Strategy: Lessons from a Postal Consolidation Operation',
    slug: 'agility-postal-consolidation-lessons', category: 'Supply Chain & Operations',
    seoTitle: 'When Agility Becomes Your Only Supply Chain Strategy | Phull Insights',
    description: 'A historical postal-consolidation case explores capacity risk, procurement options and the limits of agility without planning.',
    deck: 'The pandemic exposed the difference between improvising well and having resilience designed into the system.',
    tags: ['supply chain agility', 'capacity planning', 'S&OP'],
    why: 'Many supply chains describe themselves as agile. A sudden loss of third-party capacity tests whether that agility is supported by visibility, decision rights and alternatives.',
    evidence: 'In the historical DHL GlobalMatch case, air-capacity disruption changed procurement choices and made familiar routes harder to secure. The original analysis used supply-chain and purchasing frameworks to show how a routine sourcing decision can become a strategic constraint under stress.',
    practice: 'The transferable lesson is to identify which parts of a service promise depend on capacity controlled by someone else. Scenario planning, clear escalation and an honest view of customer priorities make a rapid response more repeatable.',
    actions: ['Map capacity dependencies by route, provider and customer promise.', 'Agree triggers for switching options before a disruption occurs.', 'Rehearse how commercial, planning and operations leaders will decide together.'],
    perspective: 'Agility is valuable, but it should not have to compensate indefinitely for a missing planning system. Resilience is the combination of options, information and authority to act.'
  },
  {
    number: 5, title: 'Before You Take the Investment: What a Luxury Bakery Teaches About Capital Decisions',
    slug: 'capital-decisions-valuation-lady-m', category: 'Commercial & Finance',
    seoTitle: 'What a Luxury Bakery Teaches About Capital Decisions | Phull Insights',
    description: 'A historical investment exercise shows how operational assumptions shape valuation and financing decisions.',
    deck: 'A persuasive investment case is only as strong as the operating assumptions beneath it.',
    tags: ['capital allocation', 'valuation', 'operations'],
    why: 'Leaders can be drawn to an attractive concept before testing what growth, costs and working capital would require in practice.',
    evidence: 'The historical luxury-bakery exercise compared valuation approaches and funding choices. It illustrated how sensitive an apparent opportunity can be to assumptions about demand, margins, expansion pace and cash needs.',
    practice: 'Operational due diligence should challenge the model: what capacity is needed, when does cash leave the business, and how much room is there for a slower ramp? A range of scenarios is more informative than one precise forecast.',
    actions: ['State the operating assumptions behind the forecast in plain language.', 'Test a slower-growth and higher-cost case before approving capital.', 'Separate the value of the business from the preferred way to finance it.'],
    perspective: 'Finance is not separate from operations. A good capital decision connects the model to what people, assets and processes can actually deliver.'
  },
  {
    number: 6, title: 'What a Stalled Insourcing Project Taught Me About the Limits of Good Intentions',
    slug: 'insourcing-project-leadership-lessons', category: 'Transformation & Governance',
    seoTitle: 'What a Stalled Insourcing Project Taught Me | Phull Insights',
    description: 'A professional reflection on why commercial logic alone cannot carry an insourcing transformation through governance and change.',
    deck: 'A sound case can still stall if the people who must deliver it are not part of the decision.',
    tags: ['insourcing', 'transformation', 'stakeholder governance'],
    why: 'Insourcing decisions are often framed around cost and control. Their delivery depends just as much on trust, ownership and an agreed account of the operational consequences.',
    evidence: 'This professional reflection examines a project that did not progress as intended. The lesson was not that the commercial logic was irrelevant, but that a proposal cannot substitute for a coalition of accountable stakeholders.',
    practice: 'A stronger approach would put the receiving teams, decision makers and affected partners into the design early. Governance should surface unresolved objections before a plan hardens into a commitment.',
    actions: ['Map who must approve, operate and live with the change.', 'Record objections and assumptions alongside the commercial case.', 'Define a decision gate that can pause the project without treating pause as failure.'],
    perspective: 'A stalled project can be valuable evidence. Good intentions and a positive spreadsheet do not remove the need to earn operational consent.'
  },
  {
    number: 7, title: 'Why Local Data Matters More Than Another Net-Zero Policy',
    slug: 'sustainability-app-dhl-local-data', category: 'Sustainable Performance',
    seoTitle: 'Local Sustainability Data Turns Targets into Action | Phull Insights',
    description: 'A historical logistics case explores how local data can make enterprise sustainability goals operational.',
    deck: 'A target at group level becomes useful when site teams can see the choices it asks them to make.',
    tags: ['sustainability data', 'logistics', 'operational performance'],
    why: 'Corporate targets can be clear while the daily decisions that support them remain invisible to local teams.',
    evidence: 'The historical DHL-related concept behind this article explored a local data application. Its value was not the app itself, but the possibility of connecting site-level activity, ownership and feedback to a broader sustainability ambition.',
    practice: 'A useful local view should show data provenance and uncertainty. It should help a manager distinguish a change in activity from a change in environmental performance, then decide what to test next.',
    actions: ['Identify the environmental decision a site manager can actually influence.', 'Check whether the local data is complete and comparable before setting a target.', 'Make the next action and its owner visible in the same review as the measure.'],
    perspective: 'Better reporting is not the end point. The value appears when evidence changes an operating choice and the result is checked.'
  },
  {
    number: 8, title: 'The Leadership Model That Finally Made Sense of How I Actually Work',
    slug: 'responsible-leadership-model-operations', category: 'Leadership & Transformation',
    seoTitle: 'Responsible Leadership in Operations | Phull Insights',
    description: 'A personal reflection on responsible leadership, values and the practical choices that shape an operating culture.',
    deck: 'Leadership models are useful when they help explain what you do under pressure, not just what you value in theory.',
    tags: ['responsible leadership', 'values', 'operations'],
    why: 'Operational leaders have to make decisions across competing needs: customers, colleagues, performance, risk and long-term capability.',
    evidence: 'This reflection draws on postgraduate leadership study and professional experience. The most useful lens was not a single ideal style, but a disciplined way to notice how personal values affect decisions and relationships.',
    practice: 'Responsible leadership becomes visible in ordinary choices: who is consulted, what evidence is challenged, what trade-off is explained, and whether a decision can be revisited when its effects become clear.',
    actions: ['Name the stakeholders who bear the cost of a decision.', 'Ask where your preferred solution may conflict with your stated values.', 'Create a review point to test the effect after implementation.'],
    perspective: 'A leadership model should increase accountability, not offer a flattering label. Its value lies in improving the next difficult decision.'
  },
  {
    number: 9, title: 'What the Ladder of Inference Does to Your Supply Chain Decisions',
    slug: 'ladder-inference-supply-chain-decisions', category: 'Leadership & Transformation',
    seoTitle: 'The Ladder of Inference in Supply Chain Decisions | Phull Insights',
    description: 'How leaders can separate observation from interpretation in supplier, team and stakeholder decisions.',
    deck: 'The story we tell ourselves about a difficult interaction can move faster than the evidence.',
    tags: ['cognitive bias', 'decision-making', 'supply chain'],
    why: 'A missed commitment or tense meeting quickly invites a conclusion about motive. That conclusion can then shape every subsequent conversation.',
    evidence: 'The Ladder of Inference is a useful way to slow this movement from observation to belief. It asks which facts were noticed, what meaning was added, and where an assumption began to look like certainty.',
    practice: 'In a supplier dispute, write down the observable event before interpreting intent. Ask what alternative explanation could fit the same facts, then test it directly with the other party.',
    actions: ['Describe the event without adjectives or attributed motives.', 'Identify the first assumption that changed the meaning of the evidence.', 'Ask a question that could disconfirm your preferred explanation.'],
    perspective: 'Reflection is not indecision. It is a way to make difficult conversations more precise and more likely to produce a workable answer.'
  },
  {
    number: 10, title: "Three People Management Lessons from One of the World's Largest Logistics Companies",
    slug: 'people-management-lessons-dhl', category: 'Leadership & Transformation',
    seoTitle: 'Three People Management Lessons from DHL | Phull Insights',
    description: 'Historical logistics-sector lessons on employee voice, development conversations and change communication.',
    deck: 'Employee voice, feedback and change communication work only when the response is visible.',
    tags: ['people management', 'employee voice', 'change'],
    why: 'Large operational systems depend on people raising problems early, receiving useful feedback and understanding why change is happening.',
    evidence: 'A historical DHL people-management analysis considered three themes: the need for a response loop after employee feedback, the value of protecting developmental conversations from pay negotiations, and the role of readiness in change.',
    practice: 'These are not claims about DHL’s current policies. They are prompts for leaders elsewhere to test whether their own surveys lead to action, their feedback conversations are candid, and their change plans fit the organisation’s capacity.',
    actions: ['Publish what was heard, who owns the response and what will be revisited.', 'Give development a conversation with room for learning, not just reward negotiation.', 'Assess capacity and readiness before deciding the pace of change.'],
    perspective: 'Good people-management systems close loops. Without a visible response, the survey, review or change message becomes an event rather than a relationship.'
  },
  {
    number: 11, title: 'Vietnam 2030: A Supply Chain Entry Perspective',
    slug: 'vietnam-2030-supply-chain-entry', category: 'Supply Chain & Operations',
    seoTitle: 'Vietnam 2030: A Supply Chain Entry Perspective | Phull Insights',
    description: 'A historical MBA group analysis reframed as a checklist for evaluating international sourcing and market-entry choices.',
    deck: 'Market attractiveness is only the start; the operating model must survive local realities.',
    tags: ['Vietnam', 'market entry', 'international sourcing'],
    why: 'Diversifying a sourcing base can reduce one dependency while introducing others. A country-level growth story is not a supplier qualification.',
    evidence: 'The original Vietnam analysis was a group MBA assignment co-authored with Cranfield colleagues. Its figures and forecasts belonged to the research period and are not presented here as current market data. The durable lesson is to assess infrastructure, regulation, labour, partners and governance together.',
    practice: 'An entry decision should compare the full landed and managed cost of supply, not just labour cost. Local advice, supplier development and a pilot are useful where quality and compliance expectations differ.',
    actions: ['Refresh country and sector data from current primary sources before committing capital.', 'Test logistics, quality and governance risks with a bounded pilot.', 'Define the conditions under which the diversification would be stopped.'],
    perspective: 'A resilient network is not simply a longer supplier list. It is a set of options that the organisation can genuinely operate and govern.'
  },
  {
    number: 12, title: 'Sixteen Branches, a Net-Zero Target, and a Leasehold Problem: What RS Locals Teaches Us About Embedded Energy Decisions',
    slug: 'rs-locals-net-zero-leasehold-energy', category: 'Sustainable Performance',
    seoTitle: 'Net Zero Across a Leasehold Branch Network | Phull Insights',
    description: 'A historical RS Locals property exercise shows why lease terms and site-level energy evidence shape decarbonisation choices.',
    deck: 'For a leased estate, some of the most important energy decisions happen before a retrofit is specified.',
    tags: ['leasehold estate', 'energy', 'net zero'],
    why: 'A national target does not tell a property team which site to renew, improve or leave. Lease terms and landlord permissions define what can be changed.',
    evidence: 'The historical RS Locals study compared building types and low-carbon options as an academic exercise. The original site count, targets and portfolio assumptions reflect that period; they are not a statement about the company’s current estate or plans.',
    practice: 'Before selecting technology, a team should understand actual energy use, remaining lease term, building condition and who owns any improvement. Heating, lighting and on-site generation may each have a role, but the ordering depends on the site.',
    actions: ['Build a site-level energy and lease inventory.', 'Include energy performance and consent provisions in property negotiations.', 'Compare interventions against the expected occupancy period and maintenance responsibilities.'],
    perspective: 'Sustainability strategy becomes operational when property, finance and site leaders use the same evidence to make the next lease decision.'
  },
  {
    number: 13, title: 'Sustainable PPE Plastics: A Historical 2030 Market Scenario',
    slug: 'rs-ppe-sustainable-plastics-2030', category: 'Sustainable Performance',
    seoTitle: 'Sustainable PPE Plastics: The 2030 Opportunity | Phull Insights',
    description: 'A historical research proposal explores circularity, supplier collaboration and the limits of sustainable-plastics claims in PPE.',
    deck: 'A sustainable product claim must meet the same performance and traceability test as the product itself.',
    tags: ['PPE', 'circularity', 'sustainable procurement'],
    why: 'Protective equipment presents a difficult materials challenge. Substitution, recycling and take-back ideas have to be tested against safety, product standards, cost and the reality of collection after use.',
    evidence: 'The original postgraduate proposal used a 2030 market scenario and suggested ambitious supplier targets. Its market sizing, share estimates and regulatory forecasts were assumptions of that research period, not verified current facts or RS Group commitments.',
    practice: 'A credible programme would start by separating product categories, understanding material composition and checking what alternatives can meet required performance. Supplier collaboration and a bounded pilot come before a portfolio-wide promise.',
    actions: ['Ask suppliers for product-level material and performance evidence.', 'Pilot one feasible category with clear safety and end-of-life criteria.', 'Publish only targets with an agreed baseline, accountable owner and verification method.'],
    perspective: 'The opportunity is to make circularity measurable without compromising protection. A bold number is not a strategy until the supply chain can support it.'
  },
  {
    number: 14, title: 'Life Cycle Assessment for a Branch Network: What RS Locals Reveals About Hidden Carbon',
    slug: 'lca-branch-network-hidden-carbon', category: 'Sustainable Performance',
    seoTitle: 'Life Cycle Assessment for a Branch Network | Phull Insights',
    description: 'A historical RS Locals LCA exercise shows how boundaries, construction impacts and lease terms affect property choices.',
    deck: 'What sits outside an energy bill can still influence a property decision.',
    tags: ['life cycle assessment', 'embodied carbon', 'property'],
    why: 'A branch can look efficient on its monthly energy bill while its construction, refurbishment and occupancy assumptions point to a different environmental picture.',
    evidence: 'The historical RS Locals academic assessment explored embodied and operational impacts within a chosen system boundary. Its estimates depended on incomplete building data and should not be treated as a verified current company footprint.',
    practice: 'Life cycle assessment is most useful when its boundary and uncertainty are visible. It can help compare a retrofit, renewal or relocation, provided the functional use and time horizon are genuinely comparable.',
    actions: ['Define the decision and assessment boundary before collecting data.', 'Record actual meter and building information separately from estimates.', 'Test how the result changes under different lease and utilisation assumptions.'],
    perspective: 'An imperfect but transparent assessment can improve a decision. Hidden assumptions, not uncertainty itself, are the bigger risk.'
  },
  {
    number: 15, title: 'Why Partial ISO 14001 Coverage Is Not Enough',
    slug: 'iso-14001-partial-coverage-rs-group', category: 'Sustainable Performance',
    seoTitle: 'Why Partial ISO 14001 Coverage Is Not Enough | Phull Insights',
    description: 'A historical audit exercise explores the difference between certification scope and environmental management across an estate.',
    deck: 'Certification can be valuable while still leaving material activity outside its boundary.',
    tags: ['ISO 14001', 'environmental management', 'audit'],
    why: 'A certificate tells a reader about its stated scope. It does not automatically describe the environmental performance of every site, activity or supplier.',
    evidence: 'The historical RS-related audit exercise considered scope, monitoring and the closure of findings. Percentages cited in the original research referred to the period studied and are intentionally not repeated as current certification coverage.',
    practice: 'A useful management system connects material impacts, competent people, monitoring and corrective action. Leaders should know which operations are in scope and how they check that an action has resolved the underlying issue.',
    actions: ['Map the certified boundary against the activities you actually manage.', 'Review open findings for verified closure and repeat causes.', 'Put environmental measures into normal operational review where they can drive action.'],
    perspective: 'ISO 14001 is a framework for management, not a result by itself. The strongest question is what changed because the system found a problem.'
  },
  {
    number: 16, title: 'Green Roofs on Industrial Buildings: The Infrastructure Innovation That Solves Four Problems at Once',
    slug: 'green-roofs-industrial-buildings-rs-group', category: 'Sustainable Performance',
    seoTitle: 'Green Roofs for Industrial Buildings | Phull Insights',
    description: 'A historical estate proposal examines the potential and constraints of green roofs for energy, biodiversity and stormwater.',
    deck: 'One intervention may create several benefits, but only where the building and lease can support it.',
    tags: ['green roofs', 'biodiversity', 'industrial estate'],
    why: 'Green roofs can be considered for stormwater, habitat, thermal performance and roof protection. Those benefits vary by climate, design and building.',
    evidence: 'The original RS-related proposal modelled a rollout and financial benefit using research-period assumptions. Those values were not verified operational outcomes and are not presented here as current savings or corporate plans.',
    practice: 'A responsible feasibility study begins with structural capacity, waterproofing, access, maintenance, landlord consent and the site’s remaining use. Pilot measures should be selected before installation so benefits can be tested rather than assumed.',
    actions: ['Screen candidate sites for structural and lease constraints.', 'Choose a pilot with a clear baseline for runoff, maintenance and energy.', 'Compare the intervention with simpler alternatives before scaling.'],
    perspective: 'Green infrastructure deserves a place in estate planning, but the business case should be built at site level and tested against actual performance.'
  },
];

const publicationOrder = [4, 6, 13, 14, 2, 9, 12, 15, 8, 10, 3, 7, 11, 16, 1, 5];
module.exports = { articles, publicationOrder };
